
port: 1337
version: latest

key: key1

api:
  server:
    http: http://localhost:1337
  client:
    http: http://localhost:1337
    ws: ws://localhost:1337


mongo:
  url: mongodb://localhost:27017/ureka?replicaSet=rs0

auth0:
  domain: ureka.eu.auth0.com
  audience: https://app.ureka.io
  scope: openid profile email
  redirectUri: http://localhost:1338/auth/callback
  clientId: ID
  clientSecret: SECRET


admins:
  - budde377@gmail.com

redis:
  host: localhost
  port: 6379


auth:
  verify:
    algorithms:
      - RS256
    audience: https://app.ureka.io
    issuer: https://ureka.eu.auth0.com/
  jwks:
    strictSsl: true
    jwksUri: https://ureka.eu.auth0.com/.well-known/jwks.json
