mongo:
  url: mongodb://mongo:27017/ureka

port: 3000

api:
  server:
    http: http://localhost:3000
  client:
    http: https://app.ureka.budde377.io
    ws: wss://app.ureka.budde377.io


auth0:
  audience: https://app.ureka.io
  redirectUri: https://app.ureka.budde377.io/auth/callback

redis:
  host: redis-master
